---
layout: post
title: '[JavaScript] 프로미스'
categories: JavaScript
author: taeyeong

date: 2021-12-12T23:53:47+0900
---
* content
{:toc}


---

자바스크립트는 비동기 처리를 위한 하나의 패턴으로 콜백 함수를 사용합니다. 하지만 전통적인 콜백 패턴은 콜백 헬로 인해 가독성이 나쁘고 비동기 처리 중 발생한 에러의 처리가 곤란하며 여러 개의 비동기 처리를 한 번에 처리하는 데도 한계가 있습니다.

ES6에서 비동기 처리를 위한 또 다른 패턴으로 프로미스가 도입되었는데요, 프로미스는 전통적인 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있습니다.

<br>

# 비동기 처리를 위한 콜백 패턴의 단점

## 콜백 헬

비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없습니다. 따라서 비동기 함수의 처리 결과(서버의 응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야 합니다.

콜백 함수를 통해 비동기 처리 결과에 대한 후속처리를 수행하는 **비동기 함수**가, 비동기 처리 결과를 가지고 또다시 **비동기 함수를 호출**해야 한다면, 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생하게 됩니다. 이를 **콜백 헬** 이라고 합니다.

<br>

## 에러 처리의 한계

비동기 처리를 위한 콜백 패턴의 문제점 중에서 가장 심각한 것은 에러 처리가 곤란하다는 것입니다.

```js
try {
  setTimeout(() => {
    throw new Error('Error');
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못함
  console.error('캐치한 에러', e);
}
```

> `try... catch... finally` 문은 에러 처리를 구현하는 방법입니다. `try... catch... finally` 문을 실행하면 먼저 try 코드 블록이 실행됩니다. 이때 try 코드 블록에 포함된 문 중에서 에러가 발생하면 해당 에러는 catch 문의 err 변수에 전달되고 catch 코드 블록이 실행됩니다. finally 코드 블록은 에러 발생과 상관없이 반드시 한 번 실행됩니다. `try... catch... finally` 문으로 에러를 처리하면 프로그램이 강제 종료되지 않습니다.

<br>

# 프로미스

프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체입니다.

## 프로미스 생성

`Promise` 생성자 함수를 `new` 연산자와 함께 호출하면 프로미스(Promise 객체)를 생성합니다. `Promise` 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는데 이 콜백 함수는 `resolve`와 `reject` 함수를 인수로 전달받습니다.

```js
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행
  if (비동기 처리 성공) {
    resolve('result');
  } else { 비동기 처리 실패
    reject('failure reaseon');
  }
});
```

`Promise` 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 비동기 처리를 수행합니다. 이때 비동기 처리가 성공하면 콜백 함수의 인수로 전달받은 `resolve` 함수를 호출하고, 비동기 처리가 실패하면 `reject` 함수를 호출합니다.

<br>

프로미스는 현재 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태 정보를 가집니다.

- pending: 비동기 처리가 아직 수행되지 않은 상태
- fulfilled: 비동기 처리가 수행된 상태(성공)
- rejected: 비동기 처리가 수행된 상태(실패)

생성된 직후의 프로미스는 기본적으로 `pending` 상태입니다. 이후 비동기 처리가 수행되면 비동기 처리 결과에 따라 다음과 같이 프로미스의 상태가 변경됩니다.

- **비동기 처리 성공**: `resolve` 함수를 호출해 프로미스를 `fulfilled` 상태로 변경합니다.
- **비동기 처리 실패**: `reject` 함수를 호출해 프로미스를 `rejected` 상태로 변경합니다.

<br>

`pending`이 아닌 상태로 비동기 처리가 수행된 상태를 `settled` 상태라고 합니다.

프로미스는 `pending` 상태에서 `fulfilled` 또는 `rejected` 상태, 즉 `settled` 상태로 변화할 수 있습니다. 하지만 일단 `settled` 상태가 되면 더는 다른 상태로 변화할 수 없습니다.

<br>

## 프로미스의 후속 처리 메서드

프로미스의 비동기 처리 상태가 변화하면 이에 따른 후속 처리를 해야합니다. 프로미스가 `fulfilled` 상태가 되면 프로미스의 처리 결과를 가지고 무언가를 해야 하고, 프로미스가 `rejected` 상태가 되면 프로미스의 처리 결과(에러)를 가지고 에러 처리를 해야합니다.

이를 위해 프로미스는 후속 메서드 `then, catch, finally`를 제공합니다.

프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출됩니다. 이떄 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달됩니다.

모든 후속 처리 메서드는 프로미스를 반환하며, 비동기로 동작합니다.

<br>

### Promise.prototype.then

`then` 메서드는 두 개의 콜백 함수를 인수로 전달받습니다.

- 첫 번째 콜백 함수는 프로미스가 `fulfilled` 상태(`resolve` 함수가 호출된 상태)가 되면 호출됩니다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받습니다.
- 두 번째 콜백 함수는 프로미스가 `rejected` 상태(`reject` 함수가 호출된 상태)가 되면 호출됩니다. 이때 콜백 함수는 프로미스의 에러를 인수로 전달받습니다.

즉, 첫 번째 콜백 함수는 비동기 처리가 성공했을 때 호출되는 성공 처리 콜백 함수이며, 두 번째 콜백 함수는 비동기 처리가 실패했을 때 호출되는 실패 처리 콜백 함수입니다.

```js
// fulfilled
new Promise((resolve) => resolve('fulfilled')).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error('rejected'))).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // Error: rejected
```

`then` 메서드는 언제나 프로미스를 반환합니다. 만약 `then` 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고, 콜백 함수가 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 `resolve` 또는 `reject`하여 프로미스를 생성해 반환합니다.

<br>

### Promise.prototype.catch

`catch` 메서드는 한 개의 콜백 함수를 인수로 전달받습니다. `catch` 메서드의 콜백 함수는 프로미스가 `rejected` 상태인 경우에만 호출됩니다.

```js
// rejected
new Promise((_, reject) => reject(new Error('rejected'))).catch((e) =>
  console.log(e)
); // Error: rejected
```

`catch` 메서드는 `then(nundefined, onRejected)`과 동일하게 동작합니다. 언제나 프로미스를 반환합니다.

<br>

### Promise.prototype.finally

`finally` 메서드는 한 개의 콜백 함수를 인수로 전달받습니다. `finally` 메서드의 콜백 함수는 프로미스의 성공이나 실패와 상관없이 무조건 한 번 호출됩니다. `finally` 메서드도 언제나 프로미스를 반환합니다.

```js
new Promise(() => {}).finally(() => console.log('finally')); // finally
```

<br>

## 프로미스의 에러 처리

비동기 처리를 위한 콜백 패턴은 에러 처리가 곤란하다는 문제가 있습니다. 프로미스를 사용하면 에러를 문제없이 처리할 수 있습니다.

비동기 처리 결과에 대한 후속 처리는 프로미스가 제공하는 후속 처리 메서드 `then, catch, finally`를 사용해 수행합니다. 비동기 처리에서 발생한 에러는 `then` 메서드의 두 번째 콜백 함수 또는 `catch` 메서드를 사용해 처리할 수 있습니다.

```javascript
// then
fetch('https://abc.blabla').then(
  (res) => console.log(res),
  (err) => console.error(err)
);

// catch
fetch('https://abc.blabla')
  .then((res) => console.log(res))
  .catch((err) => console.error(err));
```
